spring.application.name=demo


tax-service.tax-zone-one.lower-boundary = 0
tax-service.tax-zone-one.upper-boundary = 12348

tax-service.tax-zone-two.lower-boundary = 12349
tax-service.tax-zone-two.upper-boundary = 17799

tax-service.tax-zone-three.lower-boundary = 17800
tax-service.tax-zone-three.upper-boundary = 69878

tax-service.tax-zone-four.lower-boundary = 69879
tax-service.tax-zone-four.upper-boundary = 277825

tax-service.tax-zone-five.lower-boundary = 277826

